### ISSUE TITLE
there is no exit code in pynvme,pyscsi,pysats

### ISSUE THREAD

**Issue by gao7904** [jackeichen/pydiskcmd#14]
there is no exit code in pynvme,pyscsi,pysats.

It is always helpful in the use.

**Comment by jackeichen** [comment]
will look at this.

**Comment by jackeichen** [comment]
fix in 39ccc57b56564faf4e93fa4f91d9e2898a802b6c

Here is the exit code:
code: bit 0-3
        0: command success
        1: non pydiskcmd error
        2: command parameters error
        3: device operation error
        4: command build error
        5: command execute error
        6: check command return status error
        7: check command return data error
        ...
        13: function error
        14: user defined error
        15: reservd

sub-code: bit 4-7
        ...
