### ISSUE TITLE
Can pysata pyscsi be used under Windows？

### ISSUE THREAD

**Issue by haifong** [jackeichen/pydiskcmd#4]
Hello，
Is pysata pyscsi only available under linux？

I get an error when I use pysata pyscsi in Windows; pynvme works fine on Windows。

The following errors are reported：
----------------
from pyscsi.pyscsi.scsi_cdb_atapassthrough12 import ATAPassThrough12
ModuleNotFoundError: No module named 'pyscsi.pyscsi.scsi_cdb_atapassthrough12'
----------------

**Comment by jackeichen** [comment]
Yes, pysata and pyscsi are available under Windows.

Just double to check, do you install python-scsi(from https://github.com/python-scsi/python-scsi)?

**Comment by haifong** [comment]
its work, thx.
